#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerate everything in this repo that is derived from the interactive guides,
# which now live in their own repo (denimpatel/interactive-courses):
#
#   1. _data/guide_index.yml  - one entry per guide (title, absolute URL, part
#      count) plus the repo-wide totals. The homepage counters read this at
#      build time because `site.data.series.*` no longer exists here.
#   2. static redirect stubs at every old guide URL, pointing at the guide's new
#      home on https://denimpatel.github.io/interactive-courses/. About 300 of
#      them, so they are generated, never hand-written.
#
# Usage:
#   ruby scripts/sync-guides.rb [path-to-interactive-courses-checkout]
#
# Default checkout path: ../interactive-courses (a sibling of this repo).
# Run this after adding, removing, renaming or re-permaling a guide part in
# interactive-courses, then commit the result. See CLAUDE.md.

require 'yaml'
require 'date'
require 'fileutils'
require 'set'

ROOT = File.expand_path('..', __dir__)
Dir.chdir(ROOT)

GUIDES_REPO = File.expand_path(ARGV[0] || '../interactive-courses', ROOT)
GUIDES_SITE = 'https://denimpatel.github.io/interactive-courses'

sections_file = File.join(GUIDES_REPO, '_data', 'sections.yml')
unless File.exist?(sections_file)
  abort "error: #{sections_file} not found.\n" \
        "Pass the interactive-courses checkout path: ruby scripts/sync-guides.rb /path/to/interactive-courses"
end

def load_yaml(path)
  YAML.safe_load(File.read(path, encoding: 'UTF-8'), permitted_classes: [Date, Time], aliases: true) || {}
end

sections = load_yaml(sections_file)
sections = [sections] unless sections.is_a?(Array)

# ---------------------------------------------------------------------------
# Collect every guide, in section order.
# ---------------------------------------------------------------------------

guides = []
sections.each do |sec|
  Array(sec['series']).each do |sid|
    file = File.join(GUIDES_REPO, '_data', 'series', "#{sid}.yml")
    unless File.exist?(file)
      warn "warning: #{sid} is listed in interactive-courses/_data/sections.yml but #{file} is missing - skipped"
      next
    end
    doc = load_yaml(file)
    parts = Array(doc['parts'])
    appendix = Array(doc['appendix'])
    next if doc['hub'].to_s.empty?

    guides << {
      'id' => sid,
      'section' => sec['id'],
      'title' => doc['title'].to_s,
      'hub' => doc['hub'].to_s,
      'url' => GUIDES_SITE + doc['hub'].to_s,
      'parts' => parts.length,
      'appendix' => appendix.length,
      'blurb' => parts.first.is_a?(Hash) ? parts.first['blurb'].to_s : '',
      'items' => parts + appendix
    }
  end
end

total_parts = guides.sum { |g| g['parts'] }

# ---------------------------------------------------------------------------
# 1. _data/guide_index.yml
# ---------------------------------------------------------------------------

out = +"# GENERATED by scripts/sync-guides.rb - do not edit by hand.\n"
out << "#\n"
out << "# Source of truth: the denimpatel/interactive-courses repo\n"
out << "# (_data/sections.yml + _data/series/*.yml). The guides live there, so this\n"
out << "# repo cannot compute part counts from _data/series at build time; the\n"
out << "# homepage counters read this file instead. Re-run the script against an\n"
out << "# interactive-courses checkout and commit whenever a guide part changes.\n"
out << "total_parts: #{total_parts}\n"
out << "total_guides: #{guides.length}\n"
out << "total_appendix: #{guides.sum { |g| g['appendix'] }}\n"
out << "guides:\n"
guides.each do |g|
  out << "  - id: #{g['id']}\n"
  out << "    section: #{g['section']}\n"
  out << "    title: #{g['title'].inspect}\n"
  out << "    url: #{g['url']}\n"
  out << "    parts: #{g['parts']}\n"
  out << "    appendix: #{g['appendix']}\n"
  out << "    blurb: #{g['blurb'].inspect}\n"
end
File.write(File.join(ROOT, '_data', 'guide_index.yml'), out)
puts "Wrote _data/guide_index.yml: #{guides.length} guide(s), #{total_parts} part(s)."

# ---------------------------------------------------------------------------
# 2. Static redirect stubs at every old guide URL.
# ---------------------------------------------------------------------------

def stub_html(target, label)
  <<~HTML
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="refresh" content="0; url=#{target}">
    <link rel="canonical" href="#{target}">
    <meta name="robots" content="noindex">
    <title>Moved &middot; #{label}</title>
    <style>body{font:16px/1.6 system-ui,sans-serif;max-width:44rem;margin:15vh auto;padding:0 1.5rem;color:#222}a{color:#0a58ca}</style>
    </head>
    <body>
    <h1>This page moved</h1>
    <p>#{label} now lives on the interactive guides site.</p>
    <p><a href="#{target}">#{target}</a></p>
    </body>
    </html>
  HTML
end

# permalink -> stub file path (relative to ROOT)
def stub_path(permalink)
  clean = permalink.sub(%r{\A/}, '').sub(%r{/\z}, '')
  if permalink.end_with?('.html')
    clean
  elsif clean.empty?
    'index.html'
  else
    File.join(clean, 'index.html')
  end
end

# Old guide URLs must keep working: both the permalink each page had under
# /AI/ and the pre-Jekyll `legacy` URL it redirected from. A legacy URL belongs
# to one part, so it points at that part's new page, not the series hub.
stubs = {}
collisions = []

add_stub = lambda do |path, target, label|
  return if path.to_s.empty?
  rel = stub_path(path)
  if stubs.key?(rel) && stubs[rel][:target] != target
    collisions << "#{rel}: #{stubs[rel][:target]} vs #{target}"
    return
  end
  stubs[rel] = { target: target, label: label }
end

guides.each do |g|
  add_stub.call(g['hub'], g['url'], g['title'])
  g['items'].each do |item|
    next unless item.is_a?(Hash)
    permalink = item['permalink'] || item['url']
    next unless permalink
    target = GUIDES_SITE + permalink
    add_stub.call(permalink, target, item['title'].to_s)
    Array(item['legacy']).each { |legacy| add_stub.call(legacy, target, item['title'].to_s) }
  end
end

# The /math/ section hub also moved (this repo's math section was guide-only).
if guides.any? { |g| g['section'] == 'math' }
  add_stub.call('/math/', "#{GUIDES_SITE}/math/", 'Math guides')
end

stubs.each do |rel, info|
  file = File.join(ROOT, rel)
  FileUtils.mkdir_p(File.dirname(file))
  File.write(file, stub_html(info[:target], info[:label]))
end
puts "Wrote #{stubs.length} redirect stub(s)."

unless collisions.empty?
  warn "\nwarning: #{collisions.length} colliding stub path(s) left to the first series:"
  collisions.each { |c| warn "  #{c}" }
end
